language: android
sudo: required
jdk: oraclejdk8
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
env:
  global:
    - ANDROID_API=29
    - EMULATOR_API=24
    - ANDROID_BUILD_TOOLS=29.0.2
    - ADB_INSTALL_TIMEOUT=5
    - secure: SWkAxJosfVDJuKGXa27NdwxHfes7I5xoj76+/i1gpvvDAsM5Ekhk4Gn6gNHBt34g4aGz7pMtjfu6wMiYJPxb+u6kV1KOOrK9fmlUe4sBcgfMXJ0rJ2ahdOfD7jRkF7SUp3zKw91Y82kXaVFmcQuCX4jDVYh9f3miRuqA1udO2e2u9Vh6DZeeJnsRHr56GxbLcM4tyDGIxDbwgAVe1YoDYy3WzZauJ3ogbLmbybQXNTcQrc7G8M4us0vkMg81wdaTRLTiePB461hQrCVRzsAag02fuViXh1KDIQtf8Wi+IJGok6VfKFLHJAEr0zipeehfDUFgQzm2BwsF5M+PyCrzx9PmuOezbWNb/acH+bH2hpMfoEMjtJrEZkMMCtGcfrXKdG3ucMDui0Cs2UenEnITojGfAfvU0dN6kfQUo+SyxTziWYHkIjNpz5/C714YueYV3/0BFhFlcL265avLny5dVa13uYvY8HZKXOIepg/kTwZMxFdCxj4Yp8aClP77/dkY7LXe/N7hHq8v2jKdOyfdz1UyqHvXYTWDSwV6cV4y/4IN2cNb18N/vSSCCSwnacMEh/rx3QcQRy8+nFP6TEKKzQ1ZPlW/COGlUp6Pxr8VwWV3kGA6UDweLhdwHHU/i+/t9x/oE465AcIK6HsYF9M1Yh+6qYer4veXKC93QLACMBg=
    - secure: c7pUuD4vDpYM7Q5eOQ4S6ZxHv0kIWouLnADag7Q8sWaTJnqF1iNoCrQRamT9YRRrbCNMXzmdHcVOcvjs2nLqZTyTjRIUbGt1Po08PPo+dndKjLC4Co019DY7jXVVUJUaCJmS1PYlDopknQWxV6zG/ap3ytmCxKWh3Qa9pw2OdqCuk8uDtP4ebyC+yIdSidaxcwUY0EXzHBoglzII0mzwpmM4Nxb/Lb6VWxIHs+0NUhYIFnVj+DelaXcvFMD/Rc6UNGr2Ceo5Xy35QgKxNvBVroIWW98E0xn9rIK0kSFiJ2zLa9jXekJZU5ubJBXGKRNIBxxKGGybczKLwuH4Y+UpYnKcGE10+1mBWPDXtrO5VTnjqvgp1N2LhKZ5kuDEEuNtwFyeYsKe1HTYOdbPB2fokMdMXgRb33rsNZAjLwWhQB61ENCeHVJXik6rG+WoIUiX+LHbZfI/lUd6K5v8t8wugG0YdrJWwaK9gMg2dHw9h1gh1o1pLQZo/Sxln2uD3ZRCfqff+eG8XDPeOxWl0r/7IV9E5CHkJgmWVrnA+4P8gPOcfNWMaR9Lvs9L084UikB1VEATxJhFUtVtS4nopSjvH4Yn8DeTsNzA9vK0NsPNHit8r5SR04eGbfYrnxQQf7+xo0XE9iju24OkmxYHpK67y7tGrde57cTIsKxdF+Y/1wQ=
android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - android-$EMULATOR_API
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    - sys-img-armeabi-v7a-android-$ANDROID_API
    - sys-img-armeabi-v7a-android-$EMULATOR_API
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
before_install:
  - openssl aes-256-cbc -K $encrypted_0de4f5174111_key -iv $encrypted_0de4f5174111_iv
    -in keystore.jks.enc -out keystore.jks -d
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - chmod +x gradlew
  - "./gradlew dependencies || true"
script:
  - "./gradlew clean build"
before_deploy:
  - cp $TRAVIS_BUILD_DIR/keystore.jks $HOME
  - cd app/build/outputs/apk/
  - jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/keystore.jks
    -storepass $storepass -keypass $keypass app-release-unsigned.apk key0
  - jarsigner -verify app-release-unsigned.apk
  - "${ANDROID_HOME}/build-tools/29.0.2/zipalign -v 4 app-release-unsigned.apk Chart.apk"
deploy:
  provider: releases
  file: Chart.apk
  skip_cleanup: true
  on:
    repo: trunghieu2570/Chart
    tags: true
    jdk: oraclejdk8
  api_key:
    secure: "U0PjH4oDNozfDLSIqUgiWiirVe/noqtW9vei/QSmt678KgtEdQ61RYMLZ9W7VhobKeHrYVXDUFcZMxUvVV1/G7xlDEJTdoW+Q7LAb1Txbcf2op0DueDS9YXsScratEP/YxzWsCoE56yFw2k2l9470b/kX0xspD4578OScua42ZL2UEtS7Kmss8aFUOKh9pOsG/N1nW6oTC8sz+4X2dEZXTQ8QDUBEyT5HcXFpeH5WweC/xESyCVcAlY/YBdSi9rpwOxM6AbPLQCVln3u0Vas0r1TpAuR5CiV+buqjUaRFZ2xpC4UffXiVru2B1RPXm0J/gyv9jsi/6PxwTIhDqUcTaLOad1T1UDauNMBnP1GynAhoDrCq+g0AXdmTiSUMUdwei8TZK2VmEwWrJJhTrxuVVLBtyxO1g6oqmeozqehP1NulEXNsJgLzaO4dVTvTc26Y7Pfrk9raAS+a7rDu4E/NEbeA4J5fC/q4OFh7VHHZIdPeJVbuFrGp4G67co6fo7A77d3yBmEtiRrVvTwvi6GHYbtxFNE+nFJPkm2cji/Sz8iQZTjXuOfqa2EuhKTYarFxh9pws8MgwG6B/8mP6XqeKUXJurSYqvkstujdJu0baNn5AMjGB+K6h1SdRj0mCXyhYl2OpzV4io1egRWZIEd8/lGDUaTj/YE3Tq5QkCXMjc="
